easeurl = "https://mijope.de"
languageCode = "en-us"
title = "Michael Johann Peter - IT Consulting"
theme = "hugo-creative-theme"

[markup.goldmark.renderer]
unsafe= true

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Michael Johann Peter"
	description = "Freelancer/IT Consultant in the field of software engineering and IT operations. Topics include cloud environments, containerization, continuous deployments, and build pipelines. Technolgies include AWS, Terraform, Docker, Kubernetes, Jenkins, Ansible, Python, Java, Bash, Debian, CentOS, Git, Jira, Confluence, Grafana, Prometheus"

	# The path must be relative to the static folder
	favicon = "favicon.png"


	# Navigation
	[params.navigation]
		  brand = "Michael Johann Peter"
		  [params.navigation.links]
          about     = "About"
          services  = "Services"
          skills    = "Skills"
          portfolio = "Portfolio"
          cv        = "CV"
          contact   = "Contact"


	# Hero section
	[params.hero]
      # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
      slogan     = "„Knowledge is power“"
      subtitle   = "Delivering services in the field of IT operations and software engineering. <br> My goal is to boost your business by enabling your IT!"
      buttonText = "Show me more"


	# About section
	[params.about]
      headline    = "Who am I"
        description = '''IT is not only my profession but my passion <br> I am a team player <br> I love to develop solutions <br> I have a broad understanding of IT <br> I don't hesitate to learn and improve <br> Experienced remote worker'''
        buttonText  = "How can I support you?"


	# Service section
	[params.services]
		headline = "My services include"
    buttonText  = "Working with"
        [[params.services.list]]
            icon = "fas fa-code"
            title = "Software Engineering"
            description = "Enable your Engineers to deliver"
        [[params.services.list]]
            icon = "fas fa-server"
            title = "Operations"
            description = "Work with your Devs and Ops"
        [[params.services.list]]
            icon = "fas fa-cloud"
            title = "Cloud Environments"
            description = "Think Cloud Native in AWS"
        [[params.services.list]]
            icon = "fab fa-linux"
            title = "Linux Administration"
            description = "Linux and the shell is my second home"
        [[params.services.list]]
            icon = "fas fa-cogs"
            title = "Automation"
            description = "Automate your boring stuff"
        [[params.services.list]]
            icon = "fa fa-shield-alt"
            title = "IT Security"
            description = "Keep security aspects in mind"
        [[params.services.list]]
            icon = "fas fa-graduation-cap"
            title = "Trainings"
            description = "Enhance productivity and tooling"
        [[params.services.list]]
            icon = "fas fa-pencil-alt"
            title = "Publicity"
            description = "Support you in writing technical articles"


    # Skills section
    [params.skills]
        headline    = "Skills"
        description = '''<p><strong>Kubernetes | Kustomize | Flux | ArgoCD</strong></p>
        <p><strong>AWS | VMware vSphere | VirtualBox</strong></p>
        <p><strong>Terraform | Vagrant | Ansible</strong></p>
        <p><strong>Jenkins | Docker(-swarm) | Prometheus | Grafana</strong></p>
        <p><strong>Debian | Ubuntu | CentOS | SUSE | Arch | Windows</strong></p>
        <p><strong>Python | Bash | Java | Ruby | Go</strong></p>
        <p><strong>Confluence | Jira | Rally | Sharepoint</strong></p>
        <p><strong>Git | Github | Gitlab | Bitbucket | SVN</strong></p>
        <p><strong>HTML | XML | Markdown | AsciiDoc</strong></p>
        <p><strong>Nmap | Burp | Fiddler</strong></p>
        <p><strong>Apache2 | Nginx | HAProxy | Nexus</strong></p>
        '''
        buttonText  = "Experiences"


    # Portfolio scetion
	  [params.portfolio.modal]
        headline = "Some projects I have been working on"
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"


    # knowledge.rooknecht.net
	  [params.aside]
	  	  headline = "Warning! Technical stuff incoming"
		[params.aside.button]
        text = "My Knowledge Base"
        link = "https://knowledge.rootknecht.net/about"

    # cv
      [params.cv]
          headline = "More Details about me"
        [params.cv.button]
        text = "Curriculum Vitae"
        link = "https://knowledge.rootknecht.net/about"

    # Contact section
    [params.contact]
        headline = "Let's Get In Touch!"
        #description = "Feel free to contact me"
        email = "mailto:me@mijope.de"
        xing = "https://www.xing.com/profile/Michael_Peter94/"
        linkedin = "https://www.linkedin.com/in/michael-peter-4aa918107/"
        github = "https://github.com/Allaman"
        vcard = "/vcard.vcf"
